name: DeepTreeAttention
channels:
  - conda-forge
dependencies:
  - tensorflow > 2.0
  - scikit-learn
  - sphinx
  - recommonmark
  - pyyaml
  - pytest > 5.0
  - numpydoc
  - h5py
  - numpy
  - pillow
  - pip
  - matplotlib
  - rasterio
  - sphinx_rtd_theme
  - pandas
  - twine
  - yapf
  - pip:
    - opencv-python
    - sphinx-markdown-tables
    - bumpversion
    - comet_ml
    - dask
    - distributed
    - dask_jobqueue
    - tensorflow-datasets
