name: DeepTreeAttention
channels:
  - conda-forge
dependencies:
  - python=3.7
  - gdal > 3.1
  - rasterio > 1.0
  - cudatoolkit
  - scikit-learn
  - scikit-image
  - sphinx
  - recommonmark
  - pyyaml
  - descartes
  - pytest > 5.0
  - numpydoc
  - h5py == 2.10.0
  - numpy
  - pillow  
  - bokeh
  - pip
  - matplotlib
  - sphinx_rtd_theme
  - pandas
  - twine
  - yapf
  - pip:
    - tensorflow-gpu > 2.2
    - geopandas
    - rasterstats
    - opencv-python
    - sphinx-markdown-tables
    - bumpversion
    - comet_ml
    - dask
    - distributed
    - dask_jobqueue
    - tensorboard_plugin_profile
    - pydot
