train:
    classes: 21
    sensor_path: data/processed/20170218_UH_CASI_S4_NAD83_crop.tif  #path to sensor data
    ground_truth_path: data/raw/2018_IEEE_GRSS_DFC_GT_TR.tif #path to ground truth class raster
    tfrecords: /orange/ewhite/b.weinstein/Houston2018/tfrecords/train/ # Note this is not under version control, see generate.py to create locally.
    crop_size: 11
    sensor_channels: 48
    epochs: 50
    learning_rate: .001
    gpu: 2
    batch_size: 1024
    weighted_sum: True
    # Below are mostly for testing purposes, steps = 1 would train on just one batch. Set to blank for main environment to iterate over full data.
    steps:
    shuffle: True

callbacks:
    snapshots_path: /../models/
    project_name: DeepTreeAttention

#All the above parameters apply to evaluation except for paths, leave blank to ignore.
evaluation:
    tfrecords:
    sensor_path:
    ground_truth_path:
    steps:
