#Parallel workers for data generation
cpu_workers: 80

#Intermediate location to store .h5 converted geotiff hyperspec tiles
hyperspectral_tif_dir: /orange/idtrees-collab/Hyperspectral_tifs/
hyperspectral_sensor_pool: /orange/ewhite/NeonData/**/Reflectance/*.h5  #path to sensor data regex, recursive wildcards allowed
rgb_sensor_pool: /orange/ewhite/NeonData/**/Camera/**/*.tif  #path to sensor data regex, recursive wildcards allowed

train:
    species_class_file: /home/b.weinstein/DeepTreeAttention/data/processed/species_class_labels.csv
    site_class_file: /home/b.weinstein/DeepTreeAttention/data/processed/site_class_labels.csv
    domain_class_file: /home/b.weinstein/DeepTreeAttention/data/processed/domain_class_labels.csv
    min_height_diff: 10 #minimum height diffs
    checkpoint_dir: #Load RGB and HSI sub models from dir
    pretraining_dir:  #Semi-supervised HSI
    resampled_per_taxa: 50
    HSI:
        sensor_channels: 369
        crop_size: 20
        weighted_sum: True
        epochs: 120
        extend_box: 0 #expand DeepForest bounding boxes by x meters at edge
    RGB:
        sensor_channels: 3
        crop_size: 100
        weighted_sum: True
        epochs: 120
        extend_box: 0 #expand DeepForest bounding boxes by x meters at edge
    metadata:
        epochs: 80
    ensemble:
        freeze: False
        epochs: 120
    tfrecords: /orange/idtrees-collab/DeepTreeAttention/tfrecords/train/
    ground_truth_path: /home/b.weinstein/DeepTreeAttention/data/processed/train.shp  #path to ground truth class shapefile   
    learning_rate: .001
    batch_size: 256
    # Below are mostly for testing purposes, steps = 1 would train on just one batch. Set to blank for main environment to iterate over full data.
    steps:
    shuffle: True
    augment: True
    training_fraction: 0.9
    gpus: 1
    pretrain: True #Train the submodels before ensembling all together

autoencoder:
    epochs: 100
    quantile: 0.98
callbacks:
    snapshots_path: /../models/
    project_name: DeepTreeAttention

#All the above parameters apply to evaluation except for paths, leave blank to ignore.
evaluation:
    tfrecords: /orange/idtrees-collab/DeepTreeAttention/tfrecords/evaluation/
    ground_truth_path: /home/b.weinstein/DeepTreeAttention/data/processed/test.shp
    steps:

predict:
    saved_model:
    tfrecords: /orange/idtrees-collab/DeepTreeAttention/tfrecords/predict/
    savedir: /orange/idtrees-collab/DeepTreeAttention/predictions/
