#Parallel workers for data generation
cpu_workers: 50

#Intermediate location to store .h5 converted geotiff hyperspec tiles
hyperspectral_tif_dir: /orange/idtrees-collab/Hyperspectral_tifs/
hyperspectral_sensor_pool: /orange/ewhite/NeonData/**/Reflectance/*.h5  #path to sensor data regex, recursive wildcards allowed
rgb_sensor_pool: /orange/ewhite/NeonData/**/Camera/**/*.tif  #path to sensor data regex, recursive wildcards allowed

train:
    checkpoint_dir:  #Load RGB and HSI sub models from dir
    HSI:
        sensor_channels: 369
        crop_size: 20
        weighted_sum: True
        epochs: 100
    RGB:
        sensor_channels: 3
        crop_size: 100
        weighted_sum: True
        epochs: 100
    metadata:
        epochs: 200
    ensemble:
        freeze: False
        batch_size: 256
        epochs: 100
    classes: 78
    sites: 23
    tfrecords: /orange/idtrees-collab/DeepTreeAttention/tfrecords/train/
    ground_truth_path: /home/b.weinstein/DeepTreeAttention/data/processed/CHM_filtered_train.shp  #path to ground truth class shapefile   
    extend_box: 0 #expand DeepForest bounding boxes by x meters at edge
    learning_rate: .001
    batch_size: 200
    # Below are mostly for testing purposes, steps = 1 would train on just one batch. Set to blank for main environment to iterate over full data.
    steps:
    shuffle: True
    training_fraction: 0.9
    gpus: 4
    pretrain: False #Train the submodels before ensembling all together
    
callbacks:
    snapshots_path: /../models/
    project_name: DeepTreeAttention

#All the above parameters apply to evaluation except for paths, leave blank to ignore.
evaluation:
    tfrecords: /orange/idtrees-collab/DeepTreeAttention/tfrecords/evaluation/
    ground_truth_path: /home/b.weinstein/DeepTreeAttention/data/processed/test.shp
    steps:

predict:
    saved_model:
    tfrecords: /orange/idtrees-collab/DeepTreeAttention/tfrecords/predict/
    savedir: /orange/idtrees-collab/DeepTreeAttention/predictions/
